name: Dart build

on: [pull_request]

defaults:
  run:
    working-directory: ./app_dart

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          app_dart:
            - 'app_dart/**'

  check:
    timeout-minutes: 10
    needs: changes
    if: ${{ needs.changes.outputs.app_dart == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Test
        run: flutter test
  
  container:
    timeout-minutes: 10
    needs: changes
    if: ${{ needs.changes.outputs.app_dart == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Dart App
        uses: docker/build-push-action@v2
        with:
          context: app_dart
          file: app_dart/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dart:latest
      

