name: Docker build

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push Python App
        uses: docker/build-push-action@v2
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask:latest
      -
        name: Build and push Dart App
        uses: docker/build-push-action@v2
        with:
          context: app_dart
          file: app_dart/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dart:latest
