name: Python build

on:
  push:
    path:
      ./app_python
  pull_request:
    path:
      ./app_python


defaults:
  run:
    working-directory: ./app_python

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('app.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install pytz

      - name: Install requirements
        run: |
          pip install -r requirements.txt --no-cache-dir 

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')
      
      - name: Test with unittest
        run: |
          python -m unittest discover ./

      - uses: snyk/actions/python-3.8@master

      - name: Run Snyk to check for vulnerabilities
        working-directory: ./app_python
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          pip install -r requirements.txt
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --sarif-file-output=result.sarif


  container:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push Python App
        uses: docker/build-push-action@v2
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask:latest
          
          