name: Python build

on: [push, pull_request]

defaults:
  run:
    working-directory: ./app_python

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('app.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install pytz

      - name: Install requirements
        run: |
          pip install -r requirements.txt --no-cache-dir 

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')
      
      - name: Test with unittest
        run: |
          python -m unittest discover ./

      - name: Run Snyk to check for vulnerabilities
        working-directory: ./app_python
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          